require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RoutinesController do

  before (:each) do
    @user = FactoryGirl.create(:user)
    sign_in @user
  end

  # This should return the minimal set of attributes required to create a valid
  # Routine. As you add validations to Routine, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all routines as @routines" do
      routine = Routine.create! valid_attributes
      get :index, {}
      assigns(:routines).should eq([routine])
    end
  end

  describe "GET show" do
    it "assigns the requested routine as @routine" do
      routine = Routine.create! valid_attributes
      get :show, {:id => routine.to_param}
      assigns(:routine).should eq(routine)
    end
  end

  describe "GET new" do
    it "assigns a new routine as @routine" do
      get :new, {}
      assigns(:routine).should be_a_new(Routine)
    end
  end

  describe "GET edit" do
    it "assigns the requested routine as @routine" do
      routine = Routine.create! valid_attributes
      get :edit, {:id => routine.to_param}
      assigns(:routine).should eq(routine)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Routine" do
        expect {
          post :create, {:routine => valid_attributes}
        }.to change(Routine, :count).by(1)
      end

      it "assigns a newly created routine as @routine" do
        post :create, {:routine => valid_attributes}
        assigns(:routine).should be_a(Routine)
        assigns(:routine).should be_persisted
      end

      it "redirects to the created routine" do
        post :create, {:routine => valid_attributes}
        response.should redirect_to(Routine.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved routine as @routine" do
        # Trigger the behavior that occurs when invalid params are submitted
        Routine.any_instance.stub(:save).and_return(false)
        post :create, {:routine => {}}
        assigns(:routine).should be_a_new(Routine)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Routine.any_instance.stub(:save).and_return(false)
        post :create, {:routine => {}}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested routine" do
        routine = Routine.create! valid_attributes
        # Assuming there are no other routines in the database, this
        # specifies that the Routine created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Routine.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => routine.to_param, :routine => {'these' => 'params'}}
      end

      it "assigns the requested routine as @routine" do
        routine = Routine.create! valid_attributes
        put :update, {:id => routine.to_param, :routine => valid_attributes}
        assigns(:routine).should eq(routine)
      end

      it "redirects to the routine" do
        routine = Routine.create! valid_attributes
        put :update, {:id => routine.to_param, :routine => valid_attributes}
        response.should redirect_to(routine)
      end
    end

    describe "with invalid params" do
      it "assigns the routine as @routine" do
        routine = Routine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Routine.any_instance.stub(:save).and_return(false)
        put :update, {:id => routine.to_param, :routine => {}}
        assigns(:routine).should eq(routine)
      end

      it "re-renders the 'edit' template" do
        routine = Routine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Routine.any_instance.stub(:save).and_return(false)
        put :update, {:id => routine.to_param, :routine => {}}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested routine" do
      routine = Routine.create! valid_attributes
      expect {
        delete :destroy, {:id => routine.to_param}
      }.to change(Routine, :count).by(-1)
    end

    it "redirects to the routines list" do
      routine = Routine.create! valid_attributes
      delete :destroy, {:id => routine.to_param}
      response.should redirect_to(routines_url)
    end
  end

end
